// Plain-language definitions for terms used across chapters.
// Used by <Term id="..."> popovers and the Glossary page.

export interface GlossaryEntry {
  term: string
  def: string
  chapter?: string // link to the chapter that explains it in full
}

export const glossary: Record<string, GlossaryEntry> = {
  kernel: {
    term: 'Kernel',
    def: 'The core of the operating system. It runs with full control of the hardware and manages memory, processes, files and devices for all programs.',
    chapter: '/foundations/what-is-an-os',
  },
  'user-mode': {
    term: 'User mode / kernel mode',
    def: 'Two CPU privilege levels. Normal programs run in user mode and cannot touch hardware or other programs’ memory directly. The kernel runs in kernel mode and can do anything.',
    chapter: '/foundations/what-is-an-os',
  },
  syscall: {
    term: 'System call (syscall)',
    def: 'How a program asks the kernel to do something for it, such as open a file or allocate memory. The CPU switches into kernel mode, runs the kernel code, then returns.',
    chapter: '/foundations/what-is-an-os',
  },
  process: {
    term: 'Process',
    def: 'A running program. It has its own memory (address space), its own open files and one or more threads.',
    chapter: '/foundations/processes-and-threads',
  },
  thread: {
    term: 'Thread',
    def: 'A single sequence of execution inside a process. Threads of the same process share its memory.',
    chapter: '/foundations/processes-and-threads',
  },
  'context-switch': {
    term: 'Context switch',
    def: 'When the CPU stops running one thread and starts running another. The kernel saves the old thread’s state and restores the new one’s.',
    chapter: '/cpu/scheduling',
  },
  register: {
    term: 'Register',
    def: 'A tiny, very fast storage slot inside the CPU. Some hold data being computed; special ones control how the CPU behaves.',
  },
  'address-space': {
    term: 'Address space',
    def: 'The full range of memory addresses a process can use. Each process has its own, so the same address in two processes can refer to different data.',
    chapter: '/memory/virtual-memory',
  },
  'virtual-address': {
    term: 'Virtual address',
    def: 'An address as a program sees it. The hardware translates it to a physical address (a real location in RAM) on every memory access.',
    chapter: '/memory/virtual-memory',
  },
  'physical-address': {
    term: 'Physical address',
    def: 'A real location in RAM.',
    chapter: '/memory/virtual-memory',
  },
  page: {
    term: 'Page',
    def: 'A fixed-size block of virtual memory, usually 4 KiB. Memory is mapped, protected and moved one page at a time.',
    chapter: '/memory/virtual-memory',
  },
  frame: {
    term: 'Frame',
    def: 'A page-sized block of physical memory (RAM). The page table records which frame holds each page.',
    chapter: '/memory/virtual-memory',
  },
  'page-table': {
    term: 'Page table',
    def: 'A data structure, kept by the kernel for each process, that maps virtual pages to physical frames and records each page’s permissions.',
    chapter: '/memory/virtual-memory',
  },
  mmu: {
    term: 'MMU (memory management unit)',
    def: 'The part of the CPU that translates virtual addresses to physical ones on every memory access, using the page table.',
    chapter: '/memory/virtual-memory',
  },
  tlb: {
    term: 'TLB (translation lookaside buffer)',
    def: 'A small, fast cache inside the CPU of recent page-to-frame translations. It lets most memory accesses skip reading the page table.',
    chapter: '/memory/virtual-memory',
  },
  'page-fault': {
    term: 'Page fault',
    def: 'What happens when the hardware cannot translate an address, for example because the page has no frame yet. The CPU stops and asks the kernel to fix it.',
    chapter: '/memory/virtual-memory',
  },
  'huge-page': {
    term: 'Huge page',
    def: 'A larger page, usually 2 MiB or 1 GiB instead of 4 KiB. Fewer, bigger pages mean fewer translations to cache.',
    chapter: '/memory/virtual-memory',
  },
  vma: {
    term: 'Memory region (VMA)',
    def: 'A contiguous range of a process’s address space with one set of permissions and one source of data, such as the heap, the stack or a mapped file. Linux calls it a VMA (virtual memory area).',
    chapter: '/memory/virtual-memory',
  },
  mmap: {
    term: 'mmap',
    def: 'A system call that adds a memory region to a process: either empty memory or the contents of a file, readable like normal memory.',
    chapter: '/memory/kernel-memory',
  },
  'copy-on-write': {
    term: 'Copy-on-write (CoW)',
    def: 'Two processes share the same memory read-only. Only when one of them writes to a page does the kernel make a private copy of that page.',
    chapter: '/memory/kernel-memory',
  },
  'page-cache': {
    term: 'Page cache',
    def: 'File data that the kernel keeps in RAM after reading or before writing it to disk, so repeated access does not need the disk.',
    chapter: '/memory/kernel-memory',
  },
  swap: {
    term: 'Swap',
    def: 'Disk space where the kernel can move memory pages that have not been used recently, to free RAM. Reading them back is slow.',
    chapter: '/memory/kernel-memory',
  },
  rss: {
    term: 'RSS (resident set size)',
    def: 'How much of a process’s memory is actually in RAM right now.',
    chapter: '/memory/virtual-memory',
  },
  'oom-killer': {
    term: 'OOM killer',
    def: 'The Linux kernel feature that kills a process when the system runs out of memory and cannot free any more.',
    chapter: '/memory/kernel-memory',
  },
  interrupt: {
    term: 'Interrupt',
    def: 'A signal that makes the CPU pause what it is doing and run kernel code, for example when a device has data ready or another core needs attention.',
    chapter: '/foundations/what-is-an-os',
  },
  sigsegv: {
    term: 'Segmentation fault (SIGSEGV)',
    def: 'The signal the kernel sends a process that accesses memory it may not use. By default it crashes the process.',
    chapter: '/memory/virtual-memory',
  },
  fork: {
    term: 'fork',
    def: 'The Unix system call that creates a new process as a copy of the current one.',
    chapter: '/foundations/processes-and-threads',
  },
  cgroup: {
    term: 'cgroup',
    def: 'A Linux feature that limits and measures the CPU, memory and I/O a group of processes can use. Containers are built on it.',
    chapter: '/systems/virtualization',
  },
  dma: {
    term: 'DMA (direct memory access)',
    def: 'A device such as a GPU or network card copying data to or from RAM by itself, without the CPU doing the copy.',
  },
  exception: {
    term: 'Exception',
    def: 'When the CPU cannot complete the current instruction (for example a page fault or divide by zero), it stops and jumps into the kernel. The kernel either fixes the cause and re-runs the instruction, or kills the program.',
    chapter: '/foundations/what-is-an-os',
  },
  trap: {
    term: 'Trap',
    def: 'An exception a program causes on purpose with a special instruction, to ask the kernel for something. System calls and debugger breakpoints are traps. The program continues at the next instruction.',
    chapter: '/foundations/what-is-an-os',
  },
  preemption: {
    term: 'Preemption',
    def: 'The kernel taking the CPU away from a running thread without its cooperation, usually on a timer interrupt, so another thread can run.',
    chapter: '/cpu/scheduling',
  },
  scheduler: {
    term: 'Scheduler',
    def: 'The part of the kernel that decides which thread runs next on each CPU core, and for how long.',
    chapter: '/cpu/scheduling',
  },
  'file-descriptor': {
    term: 'File descriptor',
    def: 'A small number a process uses to refer to an open file, socket or pipe. 0, 1 and 2 are standard input, output and error.',
    chapter: '/io/file-systems',
  },
  libc: {
    term: 'libc (C standard library)',
    def: 'The library every C program links against. It wraps system calls in ordinary functions and adds services such as printf and malloc. On Linux it is usually glibc or musl.',
    chapter: '/foundations/what-is-an-os',
  },
  errno: {
    term: 'errno',
    def: 'A per-thread variable where libc stores the error code when a system call fails (the function itself returns -1). It is only meaningful right after a failure.',
    chapter: '/foundations/what-is-an-os',
  },
  strace: {
    term: 'strace',
    def: 'A Linux tool that shows every system call a program makes, with arguments and results. Useful for debugging, but it slows the traced program a lot.',
    chapter: '/systems/performance',
  },
  kpti: {
    term: 'KPTI (kernel page-table isolation)',
    def: 'The Linux defence against the Meltdown CPU flaw. It keeps most kernel memory out of a process’s page table while in user mode, so every kernel entry and exit switches page tables, which makes system calls more expensive.',
    chapter: '/systems/security',
  },
  'io-uring': {
    term: 'io_uring',
    def: 'A Linux interface where a program and the kernel share two queues in memory, one for requests and one for results. Many I/O operations can be submitted with one system call, or none.',
    chapter: '/io/io-models',
  },
  futex: {
    term: 'futex',
    def: 'A Linux system call that lets a thread sleep until a memory location changes. Locks use atomic instructions in user space and call futex only when a thread must wait.',
    chapter: '/cpu/concurrency-2',
  },
  'kernel-bypass': {
    term: 'Kernel bypass',
    def: 'Letting a program talk to a device such as a network card or SSD directly, without system calls on the fast path. DPDK, SPDK and RDMA work this way.',
    chapter: '/io/networking',
  },
  vdso: {
    term: 'vDSO',
    def: 'A small library the kernel maps into every process. It answers a few calls, mainly reading the clock, in user mode without a real system call.',
    chapter: '/foundations/what-is-an-os',
  },
  'monolithic-kernel': {
    term: 'Monolithic kernel',
    def: 'A kernel that runs all OS services (file systems, networking, drivers) in kernel mode as one program. Linux is monolithic.',
    chapter: '/foundations/what-is-an-os',
  },
  microkernel: {
    term: 'Microkernel',
    def: 'A kernel that keeps only threads, memory and messaging in kernel mode, and runs drivers and file systems as separate user-mode processes. Examples are seL4 and QNX.',
    chapter: '/foundations/what-is-an-os',
  },
  ipc: {
    term: 'IPC (inter-process communication)',
    def: 'Any way for processes to exchange data or signals, such as pipes, sockets, shared memory or messages.',
    chapter: '/cpu/ipc',
  },
  seccomp: {
    term: 'seccomp',
    def: 'A Linux feature that restricts which system calls a process may make. Container runtimes and browsers use it to shrink the attack surface.',
    chapter: '/systems/security',
  },
  socket: {
  term: 'Socket',
  def: 'The kernel object a program uses to send and receive data over a network (or between local processes). The program refers to it by a file descriptor.',
  chapter: '/io/networking',
  },
  'blocking-io': {
  term: 'Blocking I/O',
  def: 'An I/O call that puts the thread to sleep until it can finish, for example a read that waits for network data. It is the default for every file descriptor.',
  chapter: '/io/io-models',
  },
  'non-blocking-io': {
  term: 'Non-blocking I/O',
  def: 'An I/O mode in which a call that cannot make progress returns at once with the error EAGAIN, instead of sleeping. It is used together with a readiness API such as epoll.',
  chapter: '/io/io-models',
  },
  epoll: {
  term: 'epoll',
  def: 'The Linux interface for watching many file descriptors at once. The kernel keeps the watch list and returns only the ones that are ready, so the cost follows ready connections, not watched ones.',
  chapter: '/io/io-models',
  },
  'edge-triggered': {
  term: 'Edge-triggered / level-triggered',
  def: 'Two ways epoll can report readiness. Level-triggered reports a socket for as long as it has data. Edge-triggered reports it only when something new arrives, so the program must read until EAGAIN.',
  chapter: '/io/io-models',
  },
  'event-loop': {
  term: 'Event loop',
  def: 'One thread that waits for events on many connections (usually with epoll or kqueue), runs a short handler for each, and waits again. Handlers must never block. nginx, Redis and Node.js are built this way.',
  chapter: '/io/io-models',
  },
  backpressure: {
  term: 'Backpressure',
  def: 'Slowing a fast producer down when its consumer cannot keep up, for example by pausing reads while writes are pending, so buffers do not grow without limit.',
  chapter: '/io/io-models',
  },
  'thundering-herd': {
  term: 'Thundering herd',
  def: 'When one event, such as a new connection, wakes many waiting threads although only one of them can handle it. The rest wake up for nothing and waste CPU.',
  chapter: '/io/io-models',
  },
  'zero-copy': {
  term: 'Zero-copy',
  def: 'Moving data (for example from a file to a socket) without the CPU copying it through the program’s memory. sendfile and splice do this inside the kernel.',
  chapter: '/io/io-models',
  },
  'file-backed-memory': { term: 'File-backed memory', def: 'Memory whose contents come from a file, such as program code or a mapped data file. If unchanged, the kernel can drop it and read it from the file again.', chapter: '/memory/kernel-memory' },
  'anonymous-memory': { term: 'Anonymous memory', def: 'Memory with no file behind it: the heap, the stack and malloc blocks. The kernel can only free it by writing it to swap.', chapter: '/memory/kernel-memory' },
  'dirty-page': { term: 'Dirty page', def: 'A page changed since it was read from its file. It must be written back before its frame can be reused.', chapter: '/memory/kernel-memory' },
  'write-back': { term: 'Write-back', def: 'The kernel writing dirty page-cache pages to disk later, after write() has already returned.', chapter: '/memory/kernel-memory' },
  'buddy-allocator': { term: 'Buddy allocator', def: 'The kernel’s allocator for physical frames. It keeps free blocks in power-of-two sizes, splits them to serve requests, and merges neighbours when freed.', chapter: '/memory/kernel-memory' },
  'slab-allocator': { term: 'Slab allocator', def: 'Kernel allocator that cuts whole pages into slots for many small objects of one type, reusing freed slots.', chapter: '/memory/kernel-memory' },
  reclaim: { term: 'Reclaim', def: 'The kernel freeing frames that hold data (dropping cache, writing back or swapping pages) so they can be reused.', chapter: '/memory/kernel-memory' },
  'direct-reclaim': { term: 'Direct reclaim', def: 'When free memory is very low, a thread that asks for memory must free some itself first and waits. A common hidden cause of latency spikes.', chapter: '/memory/kernel-memory' },
  'working-set': { term: 'Working set', def: 'The pages a program is actively using right now. If working sets do not fit in RAM, the system thrashes.', chapter: '/memory/kernel-memory' },
  thrashing: { term: 'Thrashing', def: 'The system spends most of its time moving pages between RAM and disk, because the pages it evicts are needed again at once.', chapter: '/memory/kernel-memory' },
  overcommit: { term: 'Overcommit', def: 'The kernel promising processes more memory than RAM plus swap, betting that most of it is never used.', chapter: '/memory/kernel-memory' },
  psi: { term: 'PSI (pressure stall information)', def: 'Linux measure of how much time tasks lose waiting for CPU, memory or I/O, in /proc/pressure and per cgroup.', chapter: '/memory/kernel-memory' },
  vsz: { term: 'VSZ (virtual size)', def: 'The total size of a process’s memory regions, including reserved addresses that have no RAM behind them.', chapter: '/memory/kernel-memory' },
  pss: { term: 'PSS (proportional set size)', def: 'A process’s resident memory, with each shared page divided by the number of processes sharing it. PSS values add up correctly.', chapter: '/memory/kernel-memory' },
  pid: { term: 'Process ID (PID)', def: 'The number the kernel gives each process. PIDs are reused after a process is reaped.', chapter: '/foundations/processes-and-threads' },
  pcb: { term: 'Process control block (PCB)', def: 'The kernel’s record for a process or thread: state, memory, open files, signal settings. On Linux it is task_struct.', chapter: '/foundations/processes-and-threads' },
  exec: { term: 'exec', def: 'The system call family that replaces the program running in a process with a new one. The PID and open files stay the same.', chapter: '/foundations/processes-and-threads' },
  waitpid: { term: 'wait / waitpid', def: 'System calls a parent uses to wait for a child to exit and collect its exit status. This removes the child’s zombie record.', chapter: '/foundations/processes-and-threads' },
  'exit-status': { term: 'Exit status', def: 'The number from 0 to 255 a process returns when it exits; 0 means success. Shells report death by signal N as 128 + N.', chapter: '/foundations/processes-and-threads' },
  zombie: { term: 'Zombie process', def: 'A process that has exited but whose parent has not yet collected its exit status. It holds only its PID and status.', chapter: '/foundations/processes-and-threads' },
  orphan: { term: 'Orphan process', def: 'A running process whose parent has exited. The kernel gives it a new parent, PID 1 or a subreaper, which will reap it.', chapter: '/foundations/processes-and-threads' },
  clone: { term: 'clone', def: 'The Linux system call that creates a new task. Its flags choose what the new task shares with its creator, so it makes both processes and threads.', chapter: '/foundations/processes-and-threads' },
  'posix-spawn': { term: 'posix_spawn', def: 'A call that starts a new program in one step, without copying the parent like fork does. Preferred for large or multithreaded programs.', chapter: '/foundations/processes-and-threads' },
  signal: { term: 'Signal', def: 'A small numbered notification the kernel delivers to a process, such as SIGINT or SIGTERM. Each has a default action, often terminating the process.', chapter: '/foundations/processes-and-threads' },
  'signal-handler': { term: 'Signal handler', def: 'A function in a program that the kernel runs when a given signal arrives, interrupting whatever the thread was doing.', chapter: '/foundations/processes-and-threads' },
  sigterm: { term: 'SIGTERM', def: 'The polite “please exit” signal. A program can catch it and shut down cleanly. kill, docker stop and Kubernetes send it first.', chapter: '/foundations/processes-and-threads' },
  sigkill: { term: 'SIGKILL', def: 'The signal that ends a process at once. It cannot be caught, blocked or ignored, so no cleanup runs.', chapter: '/foundations/processes-and-threads' },
  'async-signal-safe': { term: 'Async-signal-safe', def: 'A function that is safe to call inside a signal handler, such as write or _exit. printf and malloc are not.', chapter: '/foundations/processes-and-threads' },
  'process-group': { term: 'Process group', def: 'A set of processes, such as one shell pipeline, that receive terminal signals like Ctrl-C together. Shells call it a job.', chapter: '/foundations/processes-and-threads' },
  session: { term: 'Session', def: 'A group of process groups, usually one login or terminal. When the terminal closes, the session gets SIGHUP.', chapter: '/foundations/processes-and-threads' },
  'pid-1': { term: 'PID 1 (init)', def: 'The first process in a system or container. It adopts orphans and must reap them, and the kernel drops signals it has no handler for.', chapter: '/foundations/processes-and-threads' },
  tini: { term: 'tini', def: 'A tiny init program to run as PID 1 in a container. It forwards signals to the real program and reaps zombies.', chapter: '/foundations/processes-and-threads' },
  'run-queue': { term: 'Run queue', def: 'The list of threads on one CPU core that are ready to run and waiting for their turn. Linux keeps one per core.', chapter: '/cpu/scheduling' },
  'time-slice': { term: 'Time slice', def: 'How long a thread may run before the scheduler may switch to another one. Also called a quantum.', chapter: '/cpu/scheduling' },
  vruntime: { term: 'Virtual runtime (vruntime)', def: 'The CPU time a thread has received, scaled by its priority weight. Linux runs threads that are furthest behind, which shares the CPU fairly.', chapter: '/cpu/scheduling' },
  cfs: { term: 'CFS (Completely Fair Scheduler)', def: 'The Linux scheduler for normal threads from 2.6.23 (2007) to 6.5. It ran the thread with the lowest virtual runtime.', chapter: '/cpu/scheduling' },
  eevdf: { term: 'EEVDF', def: 'Earliest eligible virtual deadline first: how Linux 6.6 and later picks the next normal thread. Among threads not ahead of their fair share, it runs the one with the earliest deadline.', chapter: '/cpu/scheduling' },
  nice: { term: 'Nice value', def: 'A number from -20 to 19 that sets a normal thread’s weight on Linux. Higher is “nicer”: a smaller share of the CPU when threads compete.', chapter: '/cpu/scheduling' },
  'real-time-scheduling': { term: 'Real-time scheduling (SCHED_FIFO, SCHED_RR)', def: 'Linux policies with fixed priorities 1–99. A runnable real-time thread always runs before every normal thread.', chapter: '/cpu/scheduling' },
  'priority-inversion': { term: 'Priority inversion', def: 'A high-priority thread waits for a lock held by a low-priority thread, which cannot run because medium-priority threads keep the CPU. Fixed by priority inheritance.', chapter: '/cpu/concurrency-1' },
  'cpu-affinity': { term: 'CPU affinity', def: 'The set of CPU cores a thread is allowed to run on. Set with taskset, sched_setaffinity or a cgroup cpuset.', chapter: '/cpu/scheduling' },
  'cpu-throttling': { term: 'CPU throttling (cgroup)', def: 'When a cgroup uses up its CPU quota for the current period (cpu.max), the kernel stops all its threads until the next period starts. A common cause of latency spikes in containers.', chapter: '/cpu/scheduling' },
  numa: { term: 'NUMA (non-uniform memory access)', def: 'A machine design where each CPU socket has its own memory. A core reaches its own socket’s memory faster than another socket’s.', chapter: '/memory/caches-and-numa' },
  'load-average': { term: 'Load average', def: 'The average number of threads over the last 1, 5 and 15 minutes that are runnable or, on Linux, in uninterruptible sleep (usually waiting for disk).', chapter: '/cpu/scheduling' },
  heap: { term: 'Heap', def: 'The region of a process’s memory where malloc hands out small blocks. It grows upwards as the allocator needs more space.', chapter: '/memory/allocators' },
  brk: { term: 'brk', def: 'The system call that moves the end of the heap, making it bigger or smaller. malloc uses it to get memory for small blocks.', chapter: '/memory/allocators' },
  'size-class': { term: 'Size class', def: 'One of a fixed set of block sizes an allocator rounds requests up to. Each class has its own free list, so allocation needs no searching.', chapter: '/memory/allocators' },
  fragmentation: { term: 'Fragmentation', def: 'Memory that is free or unused but cannot be used: wasted inside rounded-up blocks (internal), or split into holes too small for new requests (external).', chapter: '/memory/allocators' },
  'malloc-arena': { term: 'Arena (malloc)', def: 'One of several independent heaps inside an allocator, each with its own lock, so threads on different arenas do not wait for each other.', chapter: '/memory/allocators' },
  vfs: { term: 'VFS (virtual file system)', def: 'The kernel layer that gives programs one set of file calls (open, read, write, rename) for every file system. ext4, XFS, NFS, /proc and tmpfs each implement those calls their own way.', chapter: '/io/file-systems' },
  inode: { term: 'Inode', def: 'The record for one file: type, owner, permissions, size, timestamps, link count and where its data is on disk. It does not hold the file’s name; directories map names to inode numbers.', chapter: '/io/file-systems' },
  'hard-link': { term: 'Hard link', def: 'An extra directory entry (name) for an existing inode. All names are equal, and the file lives until the last name is removed and no process has it open.', chapter: '/io/file-systems' },
  'symbolic-link': { term: 'Symbolic link (symlink)', def: 'A small separate file that holds a path. The kernel follows the path when it is opened. It can cross file systems, and it breaks if the target is removed.', chapter: '/io/file-systems' },
  'open-file-description': { term: 'Open file description', def: 'The kernel object created by each open(): it holds the current offset and mode, and points to the inode. File descriptors from fork or dup share one, and so share the offset.', chapter: '/io/file-systems' },
  fsync: { term: 'fsync', def: 'A system call that writes a file’s changed data and metadata to stable storage, including past the drive’s cache, and waits until it is done. It is how programs make writes survive a power cut.', chapter: '/io/file-systems' },
  'o-direct': { term: 'O_DIRECT', def: 'An open() flag that makes reads and writes skip the page cache and go straight between the program’s buffer and the device. It controls caching, not durability.', chapter: '/io/file-systems' },
  journaling: { term: 'Journaling', def: 'A file system writes each change to a log (the journal) before applying it, so after a crash it can finish or discard incomplete updates instead of checking the whole disk.', chapter: '/io/file-systems' },
  linker: { term: 'Linker', def: 'The build tool (ld) that joins object files into an executable or library. It matches each use of a name with its definition and fills in addresses.', chapter: '/foundations/linking-and-loading' },
  symbol: { term: 'Symbol', def: 'A named function or global variable, as recorded in an object file or library. The linker and loader match symbols by name.', chapter: '/foundations/linking-and-loading' },
  elf: { term: 'ELF', def: 'Executable and Linkable Format: the file format of Linux executables, object files, shared libraries and core dumps.', chapter: '/foundations/linking-and-loading' },
  'shared-library': { term: 'Shared library (.so)', def: 'A library loaded when a program starts, not copied into it. Its code is shared in RAM by every process that uses it.', chapter: '/foundations/linking-and-loading' },
  'dynamic-loader': { term: 'Dynamic loader (ld.so)', def: 'The program that runs before main in a dynamically linked program. It finds and maps shared libraries and connects calls to them.', chapter: '/foundations/linking-and-loading' },
  pic: { term: 'Position-independent code (PIC)', def: 'Machine code that works at any address, using relative addresses and a table of addresses instead of fixed ones. Shared libraries must be built this way.', chapter: '/foundations/linking-and-loading' },
  pie: { term: 'Position-independent executable (PIE)', def: 'An executable built as position-independent code, so the kernel can load it at a random address. Most distributions build programs this way.', chapter: '/foundations/linking-and-loading' },
  got: { term: 'Global offset table (GOT)', def: 'A per-process table of addresses that the dynamic loader fills in. Code reads other libraries’ function and variable addresses from it.', chapter: '/foundations/linking-and-loading' },
  plt: { term: 'Procedure linkage table (PLT)', def: 'Small stubs that a call to a library function goes through. Each stub jumps to the address held in that function’s GOT slot.', chapter: '/foundations/linking-and-loading' },
  interposition: { term: 'Symbol interposition', def: 'When several loaded files define the same symbol, the first one in the loader’s search order is used by everyone. LD_PRELOAD relies on it.', chapter: '/foundations/linking-and-loading' },
  'ld-preload': { term: 'LD_PRELOAD', def: 'An environment variable naming libraries to load before all others, so their functions replace library functions such as malloc without recompiling.', chapter: '/foundations/linking-and-loading' },
  aslr: { term: 'ASLR', def: 'Address space layout randomisation: the kernel places the program, libraries, heap and stack at random addresses on each run, to make attacks harder.', chapter: '/systems/security' },
  'race-condition': { term: 'Race condition', def: 'A bug where the result depends on the timing of threads, and some timings give a wrong answer, for example two threads both incrementing a counter and losing one update.', chapter: '/cpu/concurrency-1' },
  'critical-section': { term: 'Critical section', def: 'A piece of code that touches shared data and must not run in more than one thread at a time.', chapter: '/cpu/concurrency-1' },
  'data-race': { term: 'Data race', def: 'Two threads accessing the same memory at the same time, at least one writing, without synchronisation. In C and C++ it is undefined behaviour.', chapter: '/cpu/concurrency-1' },
  'atomic-operation': { term: 'Atomic operation', def: 'A memory operation that happens as one indivisible step, such as an atomic increment or compare-and-swap. No other thread can see it half done.', chapter: '/cpu/concurrency-2' },
  spinlock: { term: 'Spinlock', def: 'A lock whose waiters loop, checking again and again, instead of sleeping. Good only for very short critical sections whose holder is running.', chapter: '/cpu/concurrency-1' },
  mutex: { term: 'Mutex', def: 'A lock that lets one thread at a time into a critical section. Waiting threads sleep. Only the thread that locked it may unlock it.', chapter: '/cpu/concurrency-1' },
  'condition-variable': { term: 'Condition variable', def: 'Lets a thread sleep, while releasing a mutex, until another thread signals that some shared state changed. Waiters must re-check the condition in a loop.', chapter: '/cpu/concurrency-1' },
  semaphore: { term: 'Semaphore', def: 'A counter that threads can wait on: wait decreases it or blocks at zero, post increases it. Used to limit concurrency or to signal between threads.', chapter: '/cpu/concurrency-1' },
  monitor: { term: 'Monitor', def: 'A language-level package of data, a lock taken automatically by every method, and condition variables. Java’s synchronized objects are monitors.', chapter: '/cpu/concurrency-1' },
  deadlock: { term: 'Deadlock', def: 'A set of threads each waiting for a resource another one holds, so none can ever continue. Usually prevented by taking locks in a fixed order.', chapter: '/cpu/concurrency-1' },
  livelock: { term: 'Livelock', def: 'Threads keep running and reacting to each other, for example retrying in step, but none makes progress.', chapter: '/cpu/concurrency-1' },
  'cpu-cache': { term: 'CPU cache', def: 'Small, fast memory inside the CPU that keeps copies of recently used main memory. L1 and L2 belong to one core; L3 is usually shared.', chapter: '/memory/caches-and-numa' },
  'cache-line': { term: 'Cache line', def: 'The fixed block of memory, usually 64 bytes, that CPU caches load and track. Reading one byte brings in its whole line.', chapter: '/memory/caches-and-numa' },
  locality: { term: 'Locality', def: 'The tendency of programs to reuse recent data (in time) and to use data near recent data (in space). Caches only help programs that have it.', chapter: '/memory/caches-and-numa' },
  prefetching: { term: 'Prefetching', def: 'The CPU loading cache lines before they are asked for, after spotting a regular access pattern. It cannot predict pointer chasing.', chapter: '/memory/caches-and-numa' },
  'cache-coherence': { term: 'Cache coherence', def: 'The hardware protocol (such as MESI) that keeps each core’s cached copy of a line consistent. Many cores may read a line, but only one may write it at a time.', chapter: '/memory/caches-and-numa' },
  'false-sharing': { term: 'False sharing', def: 'Threads writing different variables that sit in the same cache line, so the line bounces between cores and all of them slow down.', chapter: '/memory/caches-and-numa' },
  ftl: { term: 'FTL (flash translation layer)', def: 'Firmware inside an SSD that maps each block number the OS uses to wherever that data currently lives in flash. Because flash cannot be overwritten in place, it writes every update to a fresh page and cleans up later.', chapter: '/io/storage-stack' },
  'write-amplification': { term: 'Write amplification', def: 'When storage writes more data than the program asked for, for example an SSD copying still-valid pages during garbage collection. It costs bandwidth and wears out flash.', chapter: '/io/storage-stack' },
  raid: { term: 'RAID', def: 'Combining several disks into one device, by striping, mirroring or parity, for speed and to survive a disk failure. It does not protect against deletion or corruption.', chapter: '/io/storage-stack' },
  'wall-clock': { term: 'Wall clock (CLOCK_REALTIME)', def: 'The clock that tells the date and time, as seconds since 1970 UTC. It can jump forwards or backwards when it is corrected.', chapter: '/systems/time-and-timers' },
  'monotonic-clock': { term: 'Monotonic clock', def: 'A clock that only moves forward, counting from an arbitrary start such as boot. Use it to measure durations and timeouts.', chapter: '/systems/time-and-timers' },
  clocksource: { term: 'Clocksource', def: 'The hardware counter the kernel uses to keep time, such as the TSC on x86. If user code can read it, clock_gettime needs no system call.', chapter: '/systems/time-and-timers' },
  'timer-tick': { term: 'Timer tick', def: 'A regular timer interrupt on each core, often 250 or 1000 times a second. The kernel uses it for scheduling, timekeeping and coarse timers.', chapter: '/systems/time-and-timers' },
  'timer-wheel': { term: 'Timer wheel', def: 'A ring of buckets, one per tick, holding timers by expiry time. Adding and cancelling are constant time, at the cost of precision.', chapter: '/systems/time-and-timers' },
  hrtimer: { term: 'High-resolution timer (hrtimer)', def: 'A Linux kernel timer that fires at a precise moment, not at the next tick. Used for nanosleep, timerfd and the scheduler.', chapter: '/systems/time-and-timers' },
  timerfd: { term: 'timerfd', def: 'A Linux file descriptor that becomes readable when a timer expires, so an event loop can wait for timers and I/O in one call.', chapter: '/systems/time-and-timers' },
  ntp: { term: 'NTP', def: 'Network Time Protocol: how machines keep their wall clocks close to true time, usually by gently speeding up or slowing down the clock.', chapter: '/systems/time-and-timers' },
  'clock-skew': { term: 'Clock skew', def: 'The difference between the clocks of two machines. It is never exactly zero, so comparing timestamps across machines is unsafe.', chapter: '/systems/time-and-timers' },
  'virtual-machine': { term: 'Virtual machine (VM)', def: 'A fake computer made by a hypervisor, with virtual CPUs, memory and devices. Each VM runs its own operating system kernel.', chapter: '/systems/virtualization' },
  hypervisor: { term: 'Hypervisor', def: 'The software that creates and runs virtual machines and shares the real hardware between them. Examples: KVM, Xen, ESXi, Hyper-V.', chapter: '/systems/virtualization' },
  'vm-exit': { term: 'VM exit', def: 'The CPU stopping a virtual machine and switching to the hypervisor to handle an event such as a device access. Each one costs up to about a microsecond.', chapter: '/systems/virtualization' },
  'nested-paging': { term: 'Nested paging (EPT/NPT)', def: 'Two-stage address translation in hardware for VMs: guest page tables, then the hypervisor’s tables mapping guest memory to real RAM.', chapter: '/systems/virtualization' },
  virtio: { term: 'virtio', def: 'The standard family of virtual devices for VMs. Guest and host share request queues in memory, which avoids most VM exits.', chapter: '/systems/virtualization' },
  iommu: { term: 'IOMMU', def: 'A translation unit between devices and RAM, like a page table for devices. It limits which memory a device can reach, which makes device passthrough to VMs safe.', chapter: '/systems/virtualization' },
  'steal-time': { term: 'Steal time', def: 'Time a VM’s virtual CPU was ready to run but the hypervisor ran something else. Shown as “st” in top and vmstat.', chapter: '/systems/virtualization' },
  container: { term: 'Container', def: 'A group of ordinary processes that share the host kernel but get their own view of the system (namespaces), resource limits (cgroups) and their own files.', chapter: '/systems/virtualization' },
  namespace: { term: 'Namespace', def: 'A Linux feature that gives a group of processes its own private copy of one global resource, such as process IDs, network interfaces, mounts or the host name.', chapter: '/systems/virtualization' },
  overlayfs: { term: 'overlayfs', def: 'A Linux filesystem that stacks read-only directories under a writable one and shows them as one. Container images use it for their layers.', chapter: '/systems/virtualization' },
  microvm: { term: 'microVM', def: 'A virtual machine with only minimal virtual hardware, such as Firecracker, that boots in about a hundred milliseconds. Used to run untrusted containers and serverless functions.', chapter: '/systems/virtualization' },
  cas: { term: 'Compare-and-swap (CAS)', def: 'An atomic instruction that writes a new value to memory only if it still holds an expected value, and reports whether it did. The building block of locks and lock-free code.', chapter: '/cpu/concurrency-2' },
  'memory-ordering': { term: 'Memory ordering', def: 'Rules for the order in which one thread’s memory accesses become visible to others. C and C++ let each atomic operation choose: relaxed, acquire, release, or sequentially consistent.', chapter: '/cpu/concurrency-2' },
  'aba-problem': { term: 'ABA problem', def: 'A compare-and-swap succeeds because a value looks unchanged, although it changed and changed back in between, for example a freed pointer being reused.', chapter: '/cpu/concurrency-2' },
  rwlock: { term: 'Reader-writer lock', def: 'A lock that allows many readers at once, or one writer alone. Helps for long, frequent reads; its shared reader count can become a bottleneck.', chapter: '/cpu/concurrency-2' },
  rcu: { term: 'RCU (read-copy-update)', def: 'A technique where readers take no lock; writers publish a new copy of the data and free the old copy only after all earlier readers have finished. Used throughout the Linux kernel.', chapter: '/cpu/concurrency-2' },
  'time-wait': { term: 'TIME_WAIT', def: 'The TCP state the side that closes a connection first stays in (60 s on Linux), so a lost final ACK can be resent and delayed old packets expire before the same addresses and ports are reused.', chapter: '/io/networking' },
  'bandwidth-delay-product': { term: 'Bandwidth-delay product', def: 'Bandwidth × round-trip time: how much data must be in flight to keep a network path full. Socket buffers smaller than this limit one connection’s speed.', chapter: '/io/networking' },
  napi: { term: 'NAPI', def: 'How Linux receives packets under load: the first packet raises an interrupt, then the driver turns interrupts off and polls the network card’s queue in batches until it is empty.', chapter: '/io/networking' },
  'receive-side-scaling': { term: 'RSS (receive side scaling)', def: 'A network card feature that hashes each connection to one of many receive queues, each handled by a different CPU core, so traffic spreads across cores while each connection stays in order.', chapter: '/io/networking' },
  'accept-queue': { term: 'Accept queue', def: 'Connections whose TCP handshake the kernel has completed, waiting for the program to call accept(). Its size is the listen() backlog; when full, new connection attempts are ignored and clients retry.', chapter: '/io/networking' },
  xdp: { term: 'XDP (eXpress Data Path)', def: 'A Linux feature that runs a small verified eBPF program in the network driver on each incoming packet, before normal processing, to drop, redirect or pass it very cheaply.', chapter: '/io/networking' },
  rdma: { term: 'RDMA (remote direct memory access)', def: 'Network cards reading and writing another machine’s memory directly, without either CPU copying the data. Used by storage systems and GPU training clusters (InfiniBand, RoCE).', chapter: '/io/networking' },
  uid: { term: 'User ID (UID)', def: 'The number that identifies which user a process runs as. The kernel compares it with file owners to decide access.', chapter: '/systems/security' },
  root: { term: 'Root', def: 'User ID 0. The kernel lets it bypass most permission checks, so a compromised root process can do almost anything.', chapter: '/systems/security' },
  capability: { term: 'Capability (Linux)', def: 'One of about 40 separate pieces of root’s power, such as binding to ports below 1024. A process can hold only the ones it needs.', chapter: '/systems/security' },
  lsm: { term: 'Linux Security Module (LSM)', def: 'A kernel policy layer, such as SELinux or AppArmor, that can refuse an operation even for root.', chapter: '/systems/security' },
  bpf: { term: 'BPF', def: 'A small, safety-checked instruction set the kernel can run. Used for seccomp filters, packet filtering, and tracing (eBPF).', chapter: '/systems/security' },
  'buffer-overflow': { term: 'Buffer overflow', def: 'A bug where a program writes past the end of a buffer, overwriting nearby data such as a function’s return address.', chapter: '/systems/security' },
  nx: { term: 'NX (no-execute)', def: 'A page-table flag that marks memory as not executable, so data such as the stack cannot be run as code. Windows calls it DEP.', chapter: '/systems/security' },
  rop: { term: 'Return-oriented programming (ROP)', def: 'An exploit technique that chains short pieces of existing code, each ending in a return, to get around non-executable memory.', chapter: '/systems/security' },
  'stack-canary': { term: 'Stack canary', def: 'A random value the compiler places before a function’s return address and checks before returning, to detect stack buffer overflows.', chapter: '/systems/security' },
  'speculative-execution': { term: 'Speculative execution', def: 'A CPU running instructions before it knows they are needed, such as past an unresolved branch, and discarding the results if it guessed wrong.', chapter: '/systems/security' },
  'side-channel': { term: 'Side channel', def: 'A way to learn a secret indirectly, for example from how long operations take, instead of reading it.', chapter: '/systems/security' },
  meltdown: { term: 'Meltdown', def: 'A 2018 CPU flaw that let user programs read kernel memory through speculative execution. Fixed by KPTI or newer hardware.', chapter: '/systems/security' },
  spectre: { term: 'Spectre', def: 'A family of CPU flaws that trick branch prediction into leaking a program’s own data through the cache. It has many partial fixes.', chapter: '/systems/security' },
  'tail-latency': { term: 'Tail latency', def: 'The latency of the slowest requests, such as the 99th percentile (p99). Users feel it more than the average suggests.', chapter: '/systems/performance' },
  'use-method': { term: 'USE method', def: 'A performance checklist: for every resource, check Utilization (how busy), Saturation (work waiting) and Errors.', chapter: '/systems/performance' },
  'sampling-profiler': { term: 'Sampling profiler', def: 'A profiler that interrupts each CPU at a fixed rate and records the running call stack. Functions seen in more samples used more CPU. perf is one.', chapter: '/systems/performance' },
  'flame-graph': { term: 'Flame graph', def: 'A picture of many sampled call stacks: each box is a function above its caller, and its width is its share of samples.', chapter: '/systems/performance' },
  ebpf: { term: 'eBPF', def: 'A Linux feature for running small, kernel-verified programs on kernel events, such as scheduler switches or disk completions. Used for low-overhead tracing.', chapter: '/systems/performance' },
}
